### ISSUE TITLE
Testes e Depuração

### ISSUE THREAD

**Issue by JuniorJWJ** [JuniorJWJ/Programa-Conversor-de-Unidades-em-C#11]
Testar e corrigir bugs nas conversões e na interface.

**Comment by 7dann** [comment]
Todos os testes foram realizados e todos os bugs identificados foram corrigidos. No commit [9dd4e56](https://github.com/JuniorJWJ/Programa-Conversor-de-Unidades-em-C/commit/9dd4e56d31ff8075cf9e8779d2689ad46b492de0) não há mais nenhum bug aparente.
