### ISSUE TITLE
Verificar entradas do usuário

### ISSUE THREAD

**Issue by WallasFran** [JuniorJWJ/Programa-Conversor-de-Unidades-em-C#17]
Garantir que o usuário insira valores válidos e tratar erros (ex: se o usuário inserir texto em vez de números)

**Comment by wilssola** [comment]
Resolvido no menu principal com o commit f9429fcffe36ca7d519970a9ccca651cd64f70b9, falta aplicar o uso da função `input` nos outros conversores
